### ISSUE TITLE
ValueError invalid literal for int in xnli labels in train_clas.py

### ISSUE THREAD

**Issue by abedkhooli** [n-waves/ulmfit-multilingual#19]
Got ValueError: invalid literal for int() with base 10: 'neutral' while running [train_clas.py](https://github.com/n-waves/ulmfit-multilingual/blob/master/ulmfit/train_clas.py#L181)
Params:
```!python train_clas.py --data_dir 'data' --lang 'ar' --cuda_id 0 --pretrain_name 'arabic2' --model_dir 'data/models' --qrnn False --num_lm_epochs 5 --fine_tune True --max_vocab 60000 --bs 32 --bptt 70 --name='arabic2' --dataset='xnli' --bidir True --ds_pct 1.0 --train True ```
Output:
```
Dataset: xnli. Language: ar.
BiLM
Reading the data...
Reading data/xnli/XNLI-MT-1.0/multinli/multinli.train.ar.tsv...
Reading data/xnli/XNLI-1.0/xnli.test.tsv...
Reading data/xnli/XNLI-1.0/xnli.dev.tsv...
Train size: 392702. Valid size: 2490. Test size: 5010.
Traceback (most recent call last):
  File "train_clas.py", line 194, in <module>
    fire.Fire(new_train_clas)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train_clas.py", line 81, in new_train_clas
    data_clas, data_lm = get_datasets(dataset, dataset_dir, bptt, bs, lang, max_vocab, ds_pct, lm_type=lm_type)
  File "train_clas.py", line 181, in get_datasets
    lbls[split] = np.array([np.array(e, dtype=np.int) for e in lbls[split]])
  File "train_clas.py", line 181, in <listcomp>
    lbls[split] = np.array([np.array(e, dtype=np.int) for e in lbls[split]])
ValueError: invalid literal for int() with base 10: 'neutral'
``` 
Is there something I can do to the xnli dataset to avoid this error? 
Update: I already tried cleaning the 3 tsv files (removed nulls, error lines) and coded all label fields as 0, 1, 2 ( 'label' in train which seems to be the source of the error). Same error. Could that be a caching issue? I also reset kernel (colab instance is read only file system).
Update 2[solved]: issue caused by quotes in file. Rather than cleaning the tsv files, I converted labels to ints before the xnli reader returned.

**Comment by abedkhooli** [comment]
Fixed by converting labels to ints before xnli reader returns.
