### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/wiki/es-100/models/f60k/data_save.pkl'

### ISSUE THREAD

**Issue by basque21** [n-waves/ulmfit-multilingual#47]
Hi, I run `bash prepare_wiki.sh` with `$LANG=es`, and then when I try to run ` python -m ulmfit lm --dataset-path data/wiki/es-100 --tokenizer='f' --nl 3 --name 'orig' --max-vocab 60000 --lang es --qrnn=False - train 10 --bs=50 --drop_mult=0  --label-smoothing-eps=0.0` I get this exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tertiary/imanol/imanol/ulmfit-multilingual/ulmfit/__main__.py", line 188, in <module>
    fire.Fire(ULMFiT())
  File "/tertiary/imanol/imanol/env_fastai/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/tertiary/imanol/imanol/env_fastai/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/tertiary/imanol/imanol/env_fastai/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/tertiary/imanol/imanol/ulmfit-multilingual/ulmfit/pretrain_lm.py", line 163, in train_lm
    data_lm = self.load_wiki_data(bs=bs) if data_lm is None else data_lm
  File "/tertiary/imanol/imanol/ulmfit-multilingual/ulmfit/pretrain_lm.py", line 245, in load_wiki_data
    **args)
  File "/tertiary/imanol/imanol/ulmfit-multilingual/ulmfit/pretrain_lm.py", line 253, in lm_databunch
    return self.databunch(name, bunch_class=TextLMDataBunch, *args, **kwargs)
  File "/tertiary/imanol/imanol/ulmfit-multilingual/ulmfit/pretrain_lm.py", line 275, in databunch
    data = load_data(self.cache_dir, fname='lm', bs=bs)
  File "/tertiary/imanol/imanol/env_fastai/lib/python3.6/site-packages/fastai/basic_data.py", line 277, in load_data
    ll = torch.load(source, map_location='cpu') if defaults.device == torch.device('cpu') else torch.load(source)
  File "/tertiary/imanol/imanol/env_fastai/lib/python3.6/site-packages/torch/serialization.py", line 385, in load
    f = f.open('rb')
  File "/usr/lib/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/usr/lib/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'data/wiki/es-100/models/f60k/data_save.pkl'
```

In the directory `data/wiki/es-100/models/f60k/` I have `lm`, `itos.pkl` files and `lstm_orig.m` empty directory.

I'm with `torch==1.1.0` and `fastai==1.0.55` versions.

**Comment by basque21** [comment]
solved.
