### ISSUE TITLE
Error loading pretrained DE model

### ISSUE THREAD

**Issue by vilhub** [n-waves/ulmfit-multilingual#51]
Hi Piotr,

I'm facing some issues using the master branch for training a classifier from a pretrained DE model provided in the utility scripts.

I get the following error
```
Traceback (most recent call last):                                                                     
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main                     
    "__main__", mod_spec)                                                                 
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code                  
    exec(code, run_globals)                                                                        
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/ulmfit/__main__.py", line 188, in <module>
    fire.Fire(ULMFiT())                                                                                                      
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/new_env/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)                                                 
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/new_env/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)                                                                                                              
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/new_env/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)                                                               
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/ulmfit/train_clas.py", line 84, in train_cls
    learn.load('cls_best')                                                                                                            
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/new_env/lib/python3.7/site-packages/fastai/basic_train.py", line 254, in load
    get_model(self.model).load_state_dict(state, strict=strict)                                                                                       
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/new_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))                                                                     
RuntimeError: Error(s) in loading state_dict for SequentialRNN:                                                                                                                              
        Missing key(s) in state_dict: "0.module.rnns.0.linear.weight_raw", "0.module.rnns.0.linear.module.weight", "0.module.rnns.0.linear.module.bias", "0.module.rnns.1.linear.weight_raw",
 "0.module.rnns.1.linear.module.weight", "0.module.rnns.1.linear.module.bias", "0.module.rnns.2.linear.weight_raw", "0.module.rnns.2.linear.module.weight", "0.module.rnns.2.linear.module.bi
as", "0.module.rnns.3.linear.weight_raw", "0.module.rnns.3.linear.module.weight", "0.module.rnns.3.linear.module.bias".                                                                      
        Unexpected key(s) in state_dict: "0.module.rnns.0.layers.0.linear.weight_raw", "0.module.rnns.0.layers.0.linear.module.weight", "0.module.rnns.0.layers.0.linear.module.bias", "0.mod
ule.rnns.1.layers.0.linear.weight_raw", "0.module.rnns.1.layers.0.linear.module.weight", "0.module.rnns.1.layers.0.linear.module.bias", "0.module.rnns.2.layers.0.linear.weight_raw", "0.modu
le.rnns.2.layers.0.linear.module.weight", "0.module.rnns.2.layers.0.linear.module.bias", "0.module.rnns.3.layers.0.linear.weight_raw", "0.module.rnns.3.layers.0.linear.module.weight", "0.mo
dule.rnns.3.layers.0.linear.module.bias".
```

I tried several versions of fastai but if I go too far back some other requirements break.

The current requirements file I use is the following :
```
fire>=0.1.3
cupy>=5.0.0
scikit-learn>=0.20
sacremoses>=0.0.5
sentencepiece
ninja==1.9.0.post1
fastai==1.0.46
torch==1.2.0
```

Are these the correct requirements? Any other ideas to fix the issue?

I can overcome this issue by setting strict=False in the loading but it's a bit hacky and I'm not sure everything will work as expected. On IMDB I get 93.5% accuracy.

EDIT : Even with the hacky fix, evaluation fails with the error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/ulmfit/__main__.py", line 188, in <module>
    fire.Fire(ULMFiT())
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/env/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/env/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/env/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/ulmfit/train_clas.py", line 102, in train_cls
    return self.validate_cls('cls_best', bs=bs, data_cls=data_clas, data_tst=data_tst, learn=None)
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/ulmfit/train_clas.py", line 110, in validate_cls
    learn.load(save_name)
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/env/lib/python3.7/site-packages/fastai/basic_train.py", line 279, in load
    get_model(self.model).load_state_dict(state, strict=False)
  File "/home/vlaurmaa/coding/python/ulmfit-multilingual/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SequentialRNN:
        size mismatch for 1.layers.6.weight: copying a param with shape torch.Size([24, 50]) from checkpoint, the shape in current model is torch.Size([23, 50]).
        size mismatch for 1.layers.6.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([23]).
```

**Comment by vilhub** [comment]
OK so with the hacky fix I managed to overcome my second issue where validation crashes. The issue was that all the labels were not represented in the validation set due to the random split. I added a `classes` argument in the databunches so this doesn't happen and it now works.
```
data_tst = self.cls_databunch('tst', train_df=val_df, valid_df=tst_df, bs=bs, force=force, classes=list(trn_df[0].unique()), **args) # Hack to load test dataset with labels
```

I would still like to know if there is a cleaner fix for the first issue by using the correct versions of fastai / pytorch.

**Comment by PiotrCzapla** [comment]
@vilhub  you can make your validation set curated so all the labels are represented in dev valid and test. Or you can submit a PR that does that automatically, I think scilearn has function that takes care of such issues. If you consider making a PR use https://github.com/n-waves/ulmfit-multilingual/tree/multifit branch where we have an updated version of the scripts.
